---
# tasks file for ami-scan
- name: install openscap scanner
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - openscap-scanner
    - scap-security-guide

- name: create /var/tmp/roles/security directory
  file:
   path: /var/tmp/roles/security/output
   state: directory
   recurse: yes

- name: obtain rhel7 security xml content
  command: wget --quiet -O \
    /var/tmp/roles/security/Red_Hat_Enterprise_Linux_7.xml \
    https://www.redhat.com/security/data/oval/Red_Hat_Enterprise_Linux_7.xml
  

# - block:
- name: Running PCI compliance scan
  command: oscap xccdf eval \
    --profile xccdf_org.ssgproject.content_profile_pci-dss \
    --results-arf /var/tmp/roles/security/output/arf-pci-dss.xml \
    --report /var/tmp/roles/security/output/report-pci-dss.html \
    --fetch-remote-resources \
    /usr/share/xml/scap/ssg/content/ssg-amzn2-ds.xml
   ignore_errors: true

    # always:
    # - name: download report
    #   fetch:
    #     src: "{{ report }}"
    #     dest: ../oscap-reports/{{ inventory_hostname }}.html
    #     flat: yes
